# Generated by Django 4.1.4 on 2023-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog_app", "0004_alter_blog_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Authorname", models.CharField(max_length=255)),
                (
                    "Profile_image",
                    models.ImageField(default="user-default.png", upload_to="profile/"),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("youtube", models.URLField(max_length=255)),
                ("instagram", models.URLField(max_length=255)),
                ("twitter", models.URLField(max_length=255)),
                ("linkedin", models.URLField(max_length=255)),
                ("info", models.TextField()),
                ("Profile_tags", models.ManyToManyField(to="blog_app.tags")),
                ("blogs", models.ManyToManyField(to="blog_app.blog")),
            ],
        ),
    ]
