# Generated by Django 4.1.4 on 2023-03-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("author_profile", "0002_alter_author_profile_info_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author_profile",
            old_name="Profile_tags",
            new_name="tags",
        ),
    ]
