# Generated by Django 4.1.4 on 2023-03-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author_profile", "0007_alter_author_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author_profile",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
