# Generated by Django 4.1.7 on 2023-04-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_profile', '0008_alter_author_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_profile',
            name='blogs',
        ),
    ]
