# Generated by Django 4.1.4 on 2023-03-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0003_rename_name_author_authorname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to=""),
        ),
    ]
