# Generated by Django 4.1.4 on 2023-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author_profile", "0001_initial"),
        ("blog_app", "0004_alter_blog_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="author",
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ManyToManyField(to="author_profile.author_profile"),
        ),
    ]
